name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint

    - name: Type check
      run: npm run typecheck || npm run tsc # fallback to tsc if typecheck script doesn't exist

    - name: Test
      run: npm test -- --passWithNoTests # Allow tests to pass if no tests exist yet
